/**
 * osmLodgingPending.ts — AUTO-GENERATED by scripts/import_osm_lodging.py
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Re-generate with:  python scripts/import_osm_lodging.py
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * Data License: OpenStreetMap contributors (ODbL 1.0)
 * Attribution:  "Accommodation and dining location data ©
 *                OpenStreetMap contributors (ODbL)"
 * Source:       https://www.openstreetmap.org
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * ALL records in this file have verificationStatus === 'pending'.
 * They are NOT shown on the public /stay-and-eat page.
 * Review them at /admin/lodging-review and manually promote to 'verified'
 * in lodgingDining.ts after ground-truthing each entry.
 */

import type { Listing } from './lodgingDining';
import rawOsmData from './osmLodgingPending.json';

/**
 * OSM_LODGING_PENDING — all imported OSM records awaiting manual verification.
 * Safe to import in admin/review contexts only.
 */
export const OSM_LODGING_PENDING: Listing[] = rawOsmData as unknown as Listing[];
